# Consultancies in International Health

## Jobs

[UNJOBNET](https://www.unjobnet.org/){target="_blank" rel="noopener"}. All jobs in one platform. Access the complete list of job openings in all the United Nations and major international organizations. More opportunities. Less search.

[Global Health Jobs](https://globalhealthjobs.com/){target="_blank" rel="noopener"}. Over 250,000 global health professionals trust us to find verified jobs from top NGOs, public health bodies, and humanitarian groups. Your next impactful role starts here.

[Partners in Health](https://www.pih.org/){target="_blank" rel="noopener"}

APPLYING FOR UNFPA JOBS - [STEP-BY-STEP GUIDE](https://www.unfpa.org/sites/default/files/resource-pdf/Quantum%20-%20External%20Application%20Guide%20August%202022%20.pdf){target="_blank" rel="noopener"}

[Rockfeller Foundation](https://www.rockefellerfoundation.org/){target="_blank" rel="noopener"}. A Rockefeller Foundation é uma organização filantrópica global que tem como propósito promover o bem-estar da humanidade por meio de parcerias estratégicas e financiamentos orientados a resultados; atua principalmente em saúde pública, segurança alimentar, energia limpa e mudanças climáticas, inclusão financeira e inovação social, oferecendo subsídios a pesquisas e projetos, reunindo diferentes setores em fóruns colaborativos, apoiando pilotos e modelos replicáveis, e influenciando políticas públicas para gerar impactos sustentáveis e equitativos em todo o mundo.

[CFPS - China Family Panel Studies](https://cfpsdata.pku.edu.cn/#/home){target="_blank" rel="noopener"}.

[he Elizabeth Glaser Pediatric AIDS Foundation](https://pedaids.org/){target="_blank" rel="noopener"}. Founded over 30 years ago, The Elizabeth Glaser Pediatric AIDS Foundation is committed to a comprehensive response to fighting HIV and AIDS through research, global advocacy, strengthening of local health care systems, and growing the capacity of governments and communities in the world’s most affected regions to respond to urgent needs.

[Vital Strategies](https://www.vitalstrategies.org/about-us/business-and-consulting-opportunities/){target="_blank" rel="noopener"} strives to purchase high-quality goods and services at the best value in a timely and transparent manner, which includes the publication of all solicitations.

[UNICEF](https://jobs.unicef.org/en-us/listing/?jobnotfound=true){target="_blank" rel="noopener"}.

The [Clinton Health Access Initiative](https://www.clintonhealthaccess.org/about-us/#history){target="_blank" rel="noopener"} (CHAI) is a global health organization that operates at the nexus of government, business, and health. Our approach hinges on our trusted relationships with governments to drive change across entire health systems.

[VillageReach](https://www.villagereach.org/){target="_blank" rel="noopener"} transforms health care delivery to reach everyone.

At [GOPA Worldwide Consultants](https://www.gopa.de/#jump-list-target-191-0){target="_blank" rel="noopener"}, we understand that behind each development project there is a human story. For this reason, we favour dynamic development cooperation that places beneficiaries at the heart of our work.

At [DevelopmentAid](https://www.developmentaid.org/){target="_blank" rel="noopener"} we are familiar with the challenges you encounter in the development sector. Whether you’re searching for funding opportunities, partners and experts or interested in securing a job in the sector, we are ready to provide you with the most innovative business intelligence and career aid tools to assist you at every step of your way.


[evaplan GmbH at the University Hospital Heidelberg](https://www.evaplan.org/){target="_blank" rel="noopener"} is a consultancy company that undertakes advisory missions and engages in implementation and accompanying research, project implementation and capacity building in the field of international health and social protection. Our mission is to help improve the  health of populations and individuals in Low & Middle Income Countries (LMIC) in the first place. Since more than 30 years we bridge the gap between academic research and implementation striving to translate scientific knowledge and technicity into practice.

[UK Evaluation Society](https://evaluation.org.uk/about-us/){target="_blank" rel="noopener"}. Through our work, we connect people, build learning communities, provide expert-led training, and advocate for the importance of evidence-based evaluation. Our goal is to share best practice and create a safe learning environment where everyone feels welcome, can contribute and be heard.

The [Asian Development Bank](https://www.adb.org/who-we-are){target="_blank" rel="noopener"} (ADB) envisions a prosperous, inclusive, resilient, and sustainable Asia and the Pacific, while sustaining its efforts to eradicate extreme poverty in the region.

[Palladium](https://thepalladiumgroup.com/areas-expertise/health){target="_blank" rel="noopener"} strengthens local partners and communities to take a comprehensive and multifaceted approach to improving primary health care.

[management4health](https://m4health.pro/about-us/){target="_blank" rel="noopener"} was founded in 2012 as a partnership of health sector professionals specialized in the design, the implementation and the monitoring and evaluation of international health projects and programmes. Together with our partners, we work towards a shared vision of universal health coverage- accessible, affordable, appropriate health services for all- through stronger health systems. We strive for growth and development in a sustainable manner, with the aim of becoming a key stakeholder and operator in international health.


