# Health financing

Global Financing Facility ([YouTube channel](https://www.youtube.com/@GlobalFinancingFacility/videos){target="_blank" rel="noopener"} and [Website](https://www.globalfinancingfacility.org/){target="_blank" rel="noopener"}) - The Global Financing Facility for Women, Children and Adolescents (GFF) is a multi-stakeholder partnership that is helping countries tackle the greatest health and nutrition issues affecting women, children and adolescents. The GFF supports governments to bring partners together around a country-led plan, prioritizing high-impact but underinvested areas of health. The GFF Trust Fund acts as a catalyst for financing, with countries using modest GFF Trust Fund grants to significantly increase their domestic resources alongside the World Bank’s IDA and IBRD financing, aligned external financing, and private sector resources. Each relatively small external investment is multiplied by countries’ own commitments—generating a large return on investment, ultimately saving and improving lives.
