# Research tools and Partnerships


[NAPCRG](https://www.napcrg.org/){target="_blank" rel="noopener"} supports and nurtures clinicians, scientists, students and patients around the world as they pursue primary care research.


[The Building Research Capacity (BRC) Fellowship](https://www.adfm.org/programs/brc-fellowship/){target="_blank" rel="noopener"}.

[Comitê de Ética em Pesquisa do Rio de Janeiro](https://saude.prefeitura.rio/comite-de-etica-em-pesquisa/){target="_blank" rel="noopener"}.

[International Conference on Primary Health Care - ICPHC 2025](https://icphc.iphce.org/){target="_blank" rel="noopener"}.


[World Health Systems Facts](https://healthsystemsfacts.org/?_gl=1%2A1aq2uve%2A_up%2AMQ..%2A_ga%2AMTUxMzYxNjc4OS4xNzUwNDcxMTI2%2A_ga_SDY74B5S30%2AczE3NTA0NzExMjQkbzEkZzAkdDE3NTA0NzExMjQkajYwJGwwJGgw){target="_blank" rel="noopener"} is a project of the Real Reporting Foundation.

[PATH](https://www.path.org/what-we-do/){target="_blank" rel="noopener"} advances scientific research, engineers cutting-edge technologies, crafts evidence-based policies, and scales up resources, tools, and systems that transform lives. 


[Research Rabbit App](https://researchrabbitapp.com/){target="_blank" rel="noopener"} - Ferramenta que facilita a busca de conexões entre artigos científicos.

[Implementation Science and Research Practice Certificate Program](https://publichealth.jhu.edu/academics/implementation-science-and-research-practice-certificate-program){target="_blank" rel="noopener"}. Implementation Science is the study of methods to promote the adoption, integration, and sustainment of evidence-based practices, interventions or policies into practice.

[ISGlobal Barcelona Institute for Global Health](https://www.isglobal.org/en/about-us){target="_blank" rel="noopener"}. The Barcelona Institute for Global Health, ISGlobal, is the fruit of an innovative alliance between the "la Caixa" Foundation, academic institutions and government bodies to contribute to the efforts undertaken by the international community to address the challenges in global health.

O [Global Health eLearning Center](https://www.globalhealthlearning.org/pt/courses){target="_blank" rel="noopener"} (Centro de eLearning de Saúde Global oferece cursos destinados a aumentar os seus conhecimentos sobre diversas áreas técnicas de saúde global. Segue-se uma lista completa dos cursos. Os programas de certificação também incluem cursos individuais, indicados à esquerda e na página do Programa de Certificação.

[Global Health Training Center](https://globalhealthtrainingcentre.tghn.org/elearning/){target="_blank" rel="noopener"}

[TDR for research on diseases of poverty](https://tdrmooc.org/login?next=/dashboard){target="_blank" rel="noopener"}. Plataforma de ensino da UNICEF, UNDP, World Bank e WHO.

[European Commission - Research and innovation](https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe/cluster-1-health_en){target="_blank" rel="noopener"}

The [European Implementation Collaborative](https://implementation.eu/){target="_blank" rel="noopener"} engages a broad range of individual and organisational stakeholders in the field of implementation. We build links and exchange learning about implementation science and practice within Europe.

[The postgraduate study programme “International Health”](https://internationalhealth.charite.de/en/){target="_blank" rel="noopener"} is hosted by Institute of International Health at Charité – Universitäsmedizin Berlin and offers a master’s course and two diploma courses.

The [East, Central and Southern Africa Health Community](https://ecsahc.org/ecsa-hc-at-a-glance/){target="_blank" rel="noopener"} (ECSA-HC) is an inter-governmental health organization that fosters and promotes regional cooperation in health among member states. Member states of the ECSA Health Community are Kenya, Lesotho, Malawi, Mauritius, Eswatini, United Republic of Tanzania, Uganda, Zambia and Zimbabwe.

[Global Familymed Foundation](https://www.globalfamilymed.org/){target="_blank" rel="noopener"} supports Family Medicine training where access to quality health care is limited. Family Medicine graduates provide primary health care, which addresses the main health problems in the community; providing preventive, curative and rehabilitative services. We bring quality, holistic health care to those who need it the most.

## Funding

[Welcome.org](https://wellcome.org/research-funding){target="_blank" rel="noopener"} - We fund research to improve life, health and wellbeing through new knowledge and understanding.

The [German Alliance for Global Health Research](https://www.globalhealth.de/about/){target="_blank" rel="noopener"} (GLOHRA) is an association of researchers from public research institutions in Germany. We are committed to tackling today’s global health challenges via interdisciplinary and collaborative global health research.


[Independent Research Fund Denmark](https://dff.dk/en/apply-for-funding/){target="_blank" rel="noopener"} - Apply for research funding and get support for your application.

[Novo Nordisk Foundation](https://novonordiskfonden.dk/en/){target="_blank" rel="noopener"} - We are an independent, Danish enterprise foundation that supports scientific, humanitarian and social causes.



