<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Medicina Baseada em Evidências</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./testes_diagnosticos.html" rel="next">
<link href="./intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./MBE.html"><span class="chapter-title">Medicina Baseada em Evidências</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">My Notebook (Meu caderno de notas)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Artes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MBE.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Medicina Baseada em Evidências</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testes_diagnosticos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Propriedades de Testes Diagnósticos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./finding_consultancies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Consultancies in International Health</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./research.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Research tools and Partnerships</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./funding.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Funding</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./articles.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Articles by topics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução">Introdução</a></li>
  <li><a href="#fontes-que-apresentei-nas-semanas-anteriores" id="toc-fontes-que-apresentei-nas-semanas-anteriores" class="nav-link" data-scroll-target="#fontes-que-apresentei-nas-semanas-anteriores">Fontes que apresentei nas semanas anteriores:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Medicina Baseada em Evidências</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="https://deakin.libguides.com/ebp/process" target="_blank" rel="noopener">The 5 As of evidence-based practice</a> - website desenvolvido pela Dunkin University. This guide offers insights and resources for navigating the principles and procedural steps of Evidence-Based Practice.</p>
<section id="introdução" class="level2">
<h2 class="anchored" data-anchor-id="introdução">Introdução</h2>
<p>Nas semanas anteriores tivemos a oportunidade de revisar alguns conceitos da epidemiologia clínica, como prevalência, incidência, risco absoluto, risco relativo, redução absoluta do risco, número necessário a tratar (NNT) e número necessário para causar dano (NNH).</p>
<p>Usamos alguns exemplos para ilustrá-los, bem como nos exercícios propostos para a segunda semana. Mas se você prestou atenção, falamos bastante sobre as dúvidas do Dr.&nbsp;Josias ao atender a gestante Mariela. Ele se perguntava sobre a eficácia do uso de aspirina e carbonato de cálcio no seu caso. Estava em dúvida sobre qual era o real benefício do uso destes medicamentos. Reformulamos suas dúvidas usando a estratégia PICO da seguinte forma:</p>
<p><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>P (paciente ou população):</strong> gestante em risco de pré-eclâmpsia. Há uma diferença aqui quanto à população - para cada uma delas, a população muda um pouco. Para carbonato de cálcio, a população seria “estar gestante” e para aspirina a população passa a ser “gestante em risco de desenvolver pré-eclâmpsia. Vamos ver isto com detalhes mais adiante.</td>
</tr>
<tr class="even">
<td><strong>I (intervenção):</strong> temos duas no momento – (1) Aspirina e (2) carbonato de Cálcio.</td>
</tr>
<tr class="odd">
<td><strong>C (Comparação)</strong>: Nenhuma medicação ou uso de placebo. Para ambos os casos, a intervenção seria fazer ou não-fazer. Não uma comparação entre drogas distintas, com efeitos comparáveis.</td>
</tr>
<tr class="even">
<td><strong>O (Outcome)</strong>: ocorrência de pré-eclâmpsia – e demais eventos relacionados à pré-eclâmpsia que veremos adiante.</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Se você já está dominando a estratégia PICO e aproveitou para abrir os documentos e artigos das semanas passadas, já deve ter descoberto as respostas para as dúvidas do Dr.&nbsp;Josias. Se não é este o teu caso, não se preocupe. Vamos fazer esta caminhada passo a passo até chegarmos às respostas que queremos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td><p><em><code>ATENÇÃO: O caso da gestante Mariela não se resume à decisão de usar aspirina e carbonato de cálcio ou não. Sua vida, sua família, moradia e condições de vida, seu pré-natal, seu desejo ou não de ser mãe são maiores do que esta decisão e devem ser abordados pela equipe de saúde. Trabalhamos isso em diversos momentos do curso, buscando formar novos médicos que sabem olhar para o paciente e ver quem é a pessoa, sua doença e sua experiência de adoecimento.</code></em></p>
<p><em><code>Hoje, seremos SMART! Lembram disso? Trataremos de um problema específico (S) e relevante (R) para a prática clínica, com uma atividade dimensionada (T) para que reforcem os conceitos deste ciclo ao final da leitura (A) e que consigam, ao menos, perceber que este assunto é mais fácil do que parece (M).</code></em></p>
<p><em><code>Vamos nos aprofundar em um detalhe bem específico do cuidado pré-natal. Esta é uma oportunidade de mergulharmos fundo em um detalhe clínico que é percebido por muitos médicos como complicado demais. Medicina baseada em evidências não é, de forma alguma, mais importante do que possuirmos informações abrangentes sobre a paciente. Vamos apenas ser SMART e nos concentrar neste detalhe em específico por hoje.</code></em></p></td>
</tr>
</tbody>
</table>
<p><br><br></p>
</section>
<section id="fontes-que-apresentei-nas-semanas-anteriores" class="level2">
<h2 class="anchored" data-anchor-id="fontes-que-apresentei-nas-semanas-anteriores">Fontes que apresentei nas semanas anteriores:</h2>
<p><a href="https://bvsms.saude.gov.br/bvs/publicacoes/manual_gestacao_alto_risco.pdf" target="_blank" rel="noopener">Manual de Gestação de Alto Risco do Ministério da Saúde</a></p>
<p><a href="https://portaldeboaspraticas.iff.fiocruz.br/atencao-mulher/principais-questoes-sobre-profilaxia-da-pre-eclampsia-no-pre-natal/" target="_blank" rel="noopener">Principais Questões sobre Profilaxia da pré-eclâmpsia no pré-natal</a></p>
<p>Em <a href="https://www.gov.br/saude/pt-br/assuntos/noticias/2025/fevereiro/em-estrategia-contra-a-pre-eclampsia-suplementacao-de-calcio-passa-a-ser-universal-para-gestantes" target="_blank" rel="noopener">estratégia contra a pré-eclâmpsia, suplementação de cálcio passa a ser universal para gestantes</a> é a página do Ministério da Saúde apresentando esta política nacional.</p>
<p><a href="https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/notas-tecnicas/2024/nota-tecnica-conjunta-no-251-2024-coemm-cgesmu-dgci-saps-ms-e-cgan-deppros-saps-ms.pdf" target="_blank" rel="noopener">NOTA TÉCNICA CONJUNTA Nº 251/2024-COEMM/CGESMU/DGCI/SAPS/MS E CGAN/DEPPROS/SAPS/MS</a></p>
<p><a href="https://obgyn.onlinelibrary.wiley.com/doi/epdf/10.1111/1471-0528.17222" target="_blank" rel="noopener">Calcium for pre-eclampsia prevention: A systematic review and network meta-analysis to guide personalised antenatal care</a>.</p>
<p>O artigo <a href="https://www.cfp.ca/content/cfp/70/1/38.full.pdf" target="_blank" rel="noopener"><em>ASA use in patients at risk of preeclampsia</em></a>. apresenta um sumário de diversas informações sobre o impacto da aspirina na ocorrência de pré-eclâmpsia.</p>
<p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC6820858/" target="_blank" rel="noopener">Antiplatelet agents for preventing pre-eclampsia and its complications</a>.</p>
<p><a href="https://www.who.int/publications/i/item/9789240003118">WHO recommendation on calcium supplementation before pregnancy for the prevention of pre-eclampsia and its complications</a>.</p>
<p><a href="https://www.nejm.org/doi/10.1056/NEJMoa1704559?url_ver=Z39.88-2003&amp;rfr_id=ori:rid:crossref.org&amp;rfr_dat=cr_pub%20%200www.ncbi.nlm.nih.gov">Aspirin versus Placebo in Pregnancies at High Risk for Preterm Preeclampsia</a>.</p>
<p>Vamos começar respondendo a cada uma das perguntas PICO que elaboramos anteriormente. Começando pela Aspirina.</p>
<p><br><br></p>
<p><img src="images/clipboard-4133286357.png" class="img-fluid"></p>
<p><br><br></p>
<p>Neste artigo encontramos no resumo as seguintes informações:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td><p><em>In this multicenter, double-blind, placebo-controlled trial, we randomly assigned 1776 women with singleton pregnancies who were at high risk for preterm preeclampsia to receive aspirin, at a dose of 150 mg per day, or placebo from 11 to 14 weeks of gestation until 36 weeks of gestation. The primary outcome was delivery with preeclampsia before 37 weeks of gestation. The analysis was performed according to the intention-to-treat principle.</em></p>
<p><em>RESULTS A total of 152 women withdrew consent during the trial, and 4 were lost to follow up, which left 798 participants in the aspirin group and 822 in the placebo group. Preterm preeclampsia occurred in 13 participants (1.6%) in the aspirin group, as compared with 35 (4.3%) in the placebo group (odds ratio in the aspirin group, 0.38; 95% confidence interval, 0.20 to 0.74; P=0.004). Results were materially unchanged in a sensitivity analysis that took into account participants who had withdrawn or were lost to follow-up. Adherence was good, with a reported intake of 85% or more of the required number of tablets in 79.9% of the participants. There were no significant between-group differences in the incidence of neonatal adverse outcomes or other adverse events.</em></p>
<p><em>CONCLUSIONS Treatment with low-dose aspirin in women at high risk for preterm preeclampsia resulted in a lower incidence of this diagnosis than placebo.</em></p></td>
</tr>
</tbody>
</table>
<p><br><br></p>
<p>Vamos traduzir para o português e entender o que está escrito ali:</p>
<p>Neste ensaio multicêntrico, duplo-cego, controlado por placebo, <strong>foram randomizadas 1776 mulheres com gestação única e alto risco de pré-eclâmpsia prematura</strong> para receber aspirina, na dose de 150 mg por dia, ou placebo, de 11–14 semanas até 36 semanas de gestação. O desfecho primário foi o parto por pré-eclâmpsia antes de 37 semanas de gestação. A análise seguiu o princípio da intenção de tratar.</p>
<p><strong>Decifrando o que está escrito</strong> – 1776 mulheres em alto-risco de pré-eclâmpsias, metade recebeu aspirina 150mg ao dia, a outra metade recebeu placebo. Acompanharam ao longo da gestação e analisaram se desenvolviam pré-eclâmpsia antes de 37 semanas de gestação.</p>
<p><strong>Detalhe:</strong> Não precisa se preocupar com isto agora, mas se você estiver se perguntando “o que é intenção de tratar (intention-to-treat)”, é uma forma de analisar os resultados considerando todas as pacientes envolvidas no estudo desde o início. Este método aproxima mais os resultados em direção do real efeito do tratamento (efetividade do tratamento). É uma forma alternativa à análise por protocolo (per protocolo analysis), que considera somente os pacientes que concluíram o seguimento no estudo.</p>
<p><strong>RESULTADOS –</strong> Um total de 152 mulheres retirou o consentimento durante o estudo, e 4 foram perdidas ao seguimento, permanecendo 798 participantes no grupo aspirina e 822 no grupo placebo. A pré-eclâmpsia prematura ocorreu em 13 participantes (1,6 %) no grupo aspirina, em comparação com 35 (4,3 %) no grupo placebo (razão de chances [odds ratio] no grupo aspirina, 0,38; intervalo de confiança de 95 %, 0,20–0,74; P = 0,004). Os resultados mantiveram-se semelhantes em análise de sensibilidade que considerou as participantes que desistiram ou foram perdidas ao seguimento. A adesão foi satisfatória, com 79,9 % das participantes relatando ingestão de 85 % ou mais dos comprimidos prescritos. Não houve diferenças significativas entre os grupos quanto à incidência de desfechos adversos neonatais ou outros eventos adversos.</p>
<p><strong>Decifrando o que está escrito</strong> – A razão de chances (uma forma específica de risco relativo, não se preocupe com isso agora – interprete esta informação como sendo o mesmo risco relativo que você já conhece) foi de 0,38 e o intervalo de confiança variando entre 0,20 e 0,74. Este Risco Relativo de 0,38 é menor do que 1. Portanto, o risco de pré-eclâmpsia com a intervenção (aspirina 150mg ao dia) é menor do que o risco sem a aspirina – quem recebeu placebo. Se fosse maior do que 1, a aspirina aumentaria o risco de pré-eclâmpsia. Sobre a análise de sensibilidade, não se preocupe com isso agora. Nada mais é do que um escrutínio estatístico para se ter certeza de que o resultado encontrado está correto. Terminam falando que as pacientes toleraram tomar aspirina diariamente. &nbsp;</p>
<p>Dentro do artigo encontramos toda uma descrição minuciosa da metodologia – não se preocupe com isto hoje. E encontramos também uma tabela apresentando os principais resultados encontrados. Ali encontramos que 13 mulheres que tomaram aspirina e 35 que receberam placebo, desenvolveram pré-eclâmpsia. Em seguida descrevem os desfechos secundários analisados no estudo (não é o que estamos observando hoje, não se preocupe. Se concentre no desfecho primário (primary outcome), pré-eclâmpsia antes de 37 semanas de gestação.</p>
<p><br></p>
<p><img src="images/clipboard-3650889600.png" class="img-fluid"></p>
<p><br></p>
<p>Vamos nos debruçar sobre estes números agora. Veja as imagens abaixo:</p>
<p><br><br></p>
<p><img src="images/clipboard-3295726190.png" class="img-fluid"></p>
<p><br><br></p>
<p>Em porcentagem, 95,7% das mulheres em risco de desenvolver pré-eclâmpsia não tiveram pré-eclâmpsia, mas 4,3% tiveram. De onde vieram estes números? Do grupo placebo, que se comporta como a população normal, livre de intervenção. 4,3% de incidência de pré-eclâmpsia está próximo dos valores que encontramos naquele artigo brasileiro intitulado <a href="https://www.scielo.br/j/rbgo/a/qJLyYLLLvnfNC3d8hxJ68Lt/abstract/?lang=pt#:~:text=A%20frequ%C3%AAncia%20acumulada%20de%20pr%C3%A9%2Decl%C3%A2mpsia%20foi%20de,a%20hipertens%C3%A3o%20foi%20de%200%2C5%%20a%201%2C7%" target="_blank" rel="noopener"><strong>Prevalência de pré-eclâmpsia no Brasil: Uma revisão integrativa</strong></a> - 6,7% para pré-eclâmpsia, 1,7% a 6,2% para eclâmpsia e prematuridade associada a hipertensão entre 0,5% e 1,7%.</p>
<p>Na segunda coluna temos que apenas 1,6% das gestantes tiveram pré-eclâmpsia no grupo que tomou aspirina. Isto nos leva a encontrar que 2,7% das gestantes que usaram aspirina não tiveram pré-eclâmpsia. Estas 2,7% de mulheres teriam pré-eclâmpsia, se não estivessem tomando aspirina.</p>
<p>Mas e por que as mesmas 95,7% das gestantes continuaram não tendo pré-eclâmpsia? Porque não tiveram com o placebo e continuam não tendo com a aspirina. Para estas mulheres, nem o placebo, nem a aspirina fizeram diferença para elas, uma vez que não tinham e não terão pré-eclâmpsia.</p>
<p>Resumindo, de todas as mulheres que usaram aspirina (100% do braço intervenção), apenas 2,7% destas mulheres realmente se beneficiaram desta medida preventiva. 97,3% tomaram a aspirina em vão, sendo que 95,7% destas não teriam pré-eclâmpsia de qualquer maneira e 1,6% das mulheres tiveram, mesmo tomando aspirina.</p>
<p>Isto nos leva à próxima imagem, onde calculamos que 37 mulheres em risco de pré-eclâmpsia devem ganhar aspirina para que uma delas deixe de ter pré-eclâmpsia.</p>
<p><br></p>
<p><img src="images/clipboard-3524595473.png" class="img-fluid"></p>
<p><br></p>
<p>Se 37 tomaram aspirina e apenas 1 obteve o efeito desejado (evitar a ocorrência de pré-eclâmpsia), 36 tomaram a medicação em vão. De forma grosseira podemos dizer que 35 tomaram e não precisariam ter tomado, pois não teriam pré-eclâmpsia de qualquer maneira, e 1 mulher (menos do que uma, na verdade) tomou, mas teve pré-eclâmpsia mesmo assim.</p>
<p>Vamos ver se respondemos tudo o que queríamos?</p>
<p><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 97%">
</colgroup>
<tbody>
<tr class="odd">
<td><p><strong>P (paciente ou população)</strong>: gestantes em risco de pré-eclâmpsia.</p>
<p><strong>I (intervenção):</strong> Aspirina</p>
<p><strong>C (Comparação)</strong>: Nenhuma medicação ou uso de placebo.</p>
<p><strong>O (Outcome)</strong>: ocorrência de pré-eclâmpsia.</p></td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Resumindo os passos e relembrando do PICO:</p>
<ol type="1">
<li>Definimos qual a nossa população (<strong>mulheres em risco de pré-eclâmpsia);</strong></li>
<li>Encontramos o risco absoluto nesta população – esta medida veio do grupo controle que usou placebo (<strong>Comparação</strong>);</li>
<li>Encontramos o risco no grupo que recebeu a intervenção (aspirina 150mg ao dia) (<strong>Intervenção</strong>);</li>
<li>Encontramos o risco relativo, aqui chamado de odds ratio ou razão de chances.</li>
<li>Calculamos a redução absoluta do risco fazendo uma subtração simples do risco absoluto em quem recebeu placebo e o risco absoluto em quem recebeu aspirina (RAR = 4,3% - 1,6%) e encontramos 2,7%. Ou seja, a redução absoluta do risco é igual a 2,7%. Em português podemos dizer que reduzimos o risco de ocorrência de pré-eclâmpsia em 2,7%, reduzindo de 4,3% para 1,6%. <strong>(Outcome)</strong></li>
<li>Agora que conhecemos a nossa RAR (2,7%), calculamos o NNT e encontramos que 37 mulheres em risco de pré-eclâmpsia devem tomar aspirina 150 mg ao dia para que uma destas mulheres deixe de ter este problema. <strong>(Outcome)</strong></li>
</ol>
<p><br></p>
<p>Nenhuma conta complicada. Usamos apenas operações básicas que aprendemos na escola – subtração, porcentagem e regras de 3. Só isso.</p>
<p><br></p>
<p>E o carbonato de cálcio. Vamos seguir os mesmos passos. No artigo <a href="https://obgyn.onlinelibrary.wiley.com/doi/epdf/10.1111/1471-0528.17222">Calcium for pre-eclampsia prevention: A systematic review andnetwork meta-analysis to guide personalised antenatal care</a> - uma revisão sistemática e metanálise sobre o tema, encontramos o seguinte resumo:</p>
<p><br></p>
<p><img src="images/clipboard-3695179677.png" class="img-fluid"></p>
<p><br></p>
<p><img src="images/clipboard-4188042278.png" class="img-fluid"></p>
<p><br></p>
<p>Em português e com comentários:</p>
<p>A suplementação de cálcio reduz o risco de pré-eclâmpsia, mas ainda há dúvidas sobre a dosagem a prescrever e quais mulheres se beneficiam mais. <strong>Trata-se de uma revisão sistemática e metanálise sobre a suplementação de cálcio como medida preventiva para ocorrência de pré-eclâmpsia.</strong></p>
<p><strong>Objetivos:</strong> Avaliar a eficácia de doses altas (≥ 1 g/dia) e baixas (&lt; 1 g/dia) de cálcio na prevenção da pré-eclâmpsia, estratificando por ingestão dietética basal de cálcio, risco de pré-eclâmpsia, co-intervenções e momento de início da suplementação. <strong>Aqui os autores descrevem todas as comparações que serão analisadas.</strong></p>
<p><strong>Estratégia de busca:</strong> Pesquisa nas bases CENTRAL, PubMed, Global Index Medicus e CINAHL, desde a criação até 2 de fevereiro de 2021, além de registros de ensaios clínicos, listas de referências e consulta a especialistas (registro PROSPERO CRD42018111239).</p>
<p><strong>Critérios de seleção:</strong> Ensaios clínico-randomizados de suplementação de cálcio para prevenção de pré-eclâmpsia em mulheres antes ou durante a gravidez. A análise em rede incluiu também ensaios com diferentes dosagens de cálcio. <strong>Aqui os autores descrevem quais foram os tipos de estudos que entraram nas análises.</strong></p>
<p><strong>Coleta e análise de dados:</strong> Dois revisores independentes extraíram os dados publicados. A meta-análise empregou modelos de efeitos aleatórios; a análise em rede utilizou modelo bayesiano de efeitos aleatórios para estimativas de efeitos diretos e indiretos.</p>
<p><strong>Principais resultados:</strong></p>
<ul>
<li><p>Meta-análise com 30 ensaios (N = 20 445 mulheres) e análise em rede com 25 ensaios (N = 15 038).</p></li>
<li><p>A suplementação de cálcio preveniu pré-eclâmpsia de forma semelhante em altas doses (RR 0,49; IC 95% 0,36–0,66) e baixas doses (RR 0,49; IC 95% 0,36–0,65). <strong>Não houve diferença no efeito entre alta e baixa dose.</strong></p></li>
<li><p>Pela análise em rede, não houve diferença entre dose alta e dose baixa (RR 0,79; IC 95% 0,43–1,40).</p></li>
<li><p>O efeito foi consistente independentemente do risco basal de pré-eclâmpsia, da co-administração de vitamina D e do momento de início da suplementação.</p></li>
<li><p>Não houve benefício em mulheres com ingestão dietética média de cálcio considerada adequada.</p></li>
</ul>
<p>Dentro do artigo encontramos a seguinte tabela, que nos mostra as análises para altas doses de cálcio, baixas doses de cálcio e combinação entre os dois grupos, ao final. Os resultados estão circulados em vermelho.</p>
<p><br></p>
<p><img src="images/clipboard-3844703731.png" class="img-fluid"></p>
<p>Vamos relembrar os passos que demos na nossa análise para a aspirina.</p>
<p><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 97%">
</colgroup>
<tbody>
<tr class="odd">
<td><p><strong>P (paciente ou população)</strong>: gestantes em risco de pré-eclâmpsia.</p>
<p><strong>I (intervenção):</strong> carbonato de cálcio</p>
<p><strong>C (Comparação)</strong>: Nenhuma medicação ou uso de placebo.</p>
<p><strong>O (Outcome)</strong>: ocorrência de pré-eclâmpsia.</p></td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Resumindo os passos e relembrando do PICO:</p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Definimos qual a nossa população (<strong>mulheres em risco de pré-eclâmpsia);</strong></p>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Encontramos o risco absoluto nesta população – esta medida veio do grupo controle que usou placebo (<strong>Comparação</strong>) – <strong>podemos usar a mesma medida do nosso estudo anterior e do artigo brasileiro, com um valor entre 4 e 6% das gestantes em risco desenvolvendo pré-eclâmpsia ao longo da gestação.</strong></p>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Encontramos o risco no grupo que recebeu a intervenção (carbonato de cálcio) (<strong>Intervenção</strong>) – aqui teremos que fazer o caminho inverso. Encontrar o risco absoluto em quem recebeu o carbonato de cálcio a partir do risco relativo;</p>
<p>4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Encontramos o risco relativo – Carbonato de cálcio alta dose (RR 0,49; IC 95% 0,36–0,66) e baixas doses (RR 0,49; IC 95% 0,36–0,65). <strong>Não houve diferença no efeito entre alta e baixa dose.</strong></p>
<p>Agora vamos calcular o risco absoluto em quem usou <strong>carbonato de cálcio</strong>. Partindo de um número inteiro (5%), se temos um risco relativo de 0,49 para altas e baixas doses, teremos que o Risco Absoluto em quem usou carbonato de cálcio no valor de 2,5%. Em outras palavras, não usando Carbonato de Cálcio o risco absoluto de pré-eclâmpsia é de 5%. Usando Carbonato de Cálcio o risco absoluto para pré-eclâmpsia reduz para 2,5%. Agora podemos calcular a <strong>Redução Absoluta do Risco</strong>.</p>
<p>5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Calculamos a <strong>Redução Absoluta do Risco</strong> fazendo uma subtração simples do risco absoluto em quem recebeu placebo e o risco absoluto em quem recebeu carbonato de cálcio (RAR = 5,0% - 2,5%) e encontramos 2,5%. Ou seja, a redução absoluta do risco é igual a 2,5%. Em português podemos dizer que reduzimos o risco de ocorrência de pré-eclâmpsia em 2,5%, reduzindo de 5,0% para 2,5%. <strong>(Outcome)</strong></p>
<p>6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Agora que conhecemos a nossa RAR (2,5%), calculamos o NNT e encontramos que 40 mulheres em risco de pré-eclâmpsia devem tomar carbonato de cálcio para que uma destas mulheres deixe de ter este problema. <strong>(Outcome)</strong></p>
<p><br><br></p>
<p><img src="images/clipboard-2944778357.png" class="img-fluid"></p>
<p><br><br></p>
<p><img src="images/clipboard-1635376182.png" class="img-fluid"></p>
<p><br><br></p>
<p>Frente a esta situação, Dr.&nbsp;Josias pode ficar mais tranquilo de saber que tanto a Aspirina quanto a suplementação com carbonato de cálcio produzem benefícios consideráveis para prevenção de pré-eclâmpsia em gestantes. No caso da sua paciente, a gestante Mariela, que tinha medidas de pressão arterial elevadas previamente à gestação, pode ser considerada como hipertensão arterial prévia a gestação – um fator de risco para pré-eclâmpsia. Com isto, devemos começar tanto a aspirina em baixas doses quanto a suplementação de cálcio. Contudo, ele não começou estas medicações somente por que o protocolo ministerial orienta, mas sim por que, em concordância com as recomendações ministeriais e baseado em boas evidências científicas, sabe agora que o risco absoluto de pré-eclâmpsia para Mariela pode se reduzir em torno de 50% a 65% e que ao prescrever aspirina e carbonato de cálcio para 30 a 40 mulheres grávidas com perfil semelhante ao de Mariela, ao menos uma deixará de desenvolver pré-eclâmpsia e terá um final de gestação com menos eventos adversos.</p>
<p>Em tempo – este parágrafo acima é uma generalização. Não tome os valores ao pé da letra, pois não podemos afirmar com certeza que Mariela será a pessoa que se beneficiará destas medidas preventivas.</p>
<p><br><br></p>
<table class="caption-top table">
<colgroup>
<col style="width: 100%">
</colgroup>
<tbody>
<tr class="odd">
<td><p><em><code>Mais um detalhe sobre a gestante Mariela. Falamos no começo deste documento que a gestante Mariela, sua vida, sua família e sua gestação era muito mais do que uma única decisão – fazer ou não aspirina e carbonato de cálcio.</code></em></p>
<p><em><code>Foi importante lembrar disso no começo. Agora, nesta última página, acredito que vocês se sintam mais capazes de encarar discussões sobre medicina baseada em evidências. Aos poucos, vamos aprendendo a combinar estas habilidades com o método clínico centrado na pessoa e tudo aquilo que aprendemos sobre saber olhar para o paciente, ver quem é a pessoa, sua doença, sua experiência de adoecimento.</code></em></p></td>
</tr>
</tbody>
</table>
<p><br><br></p>
<p>Qual a diferença entre fazer todo este percurso que fizemos nestas semanas e simplesmente seguir o protocolo recomendado pelo Ministério da Saúde? Pode até parecer que foi um trabalho desnecessário, mas agora vocês conhecem um pouco mais o que está dentro desta caixa-preta, como funcionam as comparações e as estatísticas por trás de uma recomendação profilática como esta.</p>
<p>Por ora, todos vocês precisam se apropriar cada vez mais destes princípios da Prática Clínica Baseada em Evidências. Isto tornará a prática de todos trará.</p>
<p>Possivelmente muitos de vocês ocuparão cargos de gestão em diversos níveis no futuro. Ter domínio destas ferramentas é fundamental para poder <strong>pautar decisões e desenhar políticas baseadas em evidências.</strong></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro.html" class="pagination-link" aria-label="Artes">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Artes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./testes_diagnosticos.html" class="pagination-link" aria-label="Propriedades de Testes Diagnósticos">
        <span class="nav-page-text"><span class="chapter-title">Propriedades de Testes Diagnósticos</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>