<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Propriedades de Testes Diagnósticos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./finding_consultancies.html" rel="next">
<link href="./MBE.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./testes_diagnosticos.html"><span class="chapter-title">Propriedades de Testes Diagnósticos</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">My Notebook (Meu caderno de notas)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Artes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MBE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Medicina Baseada em Evidências</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testes_diagnosticos.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Propriedades de Testes Diagnósticos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./finding_consultancies.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Consultancies in International Health</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./research.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Research tools and Partnerships</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./funding.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Funding</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./articles.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Articles by topics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#risco-absoluto-fator-de-risco-e-fator-de-proteção" id="toc-risco-absoluto-fator-de-risco-e-fator-de-proteção" class="nav-link active" data-scroll-target="#risco-absoluto-fator-de-risco-e-fator-de-proteção">Risco Absoluto, Fator de Risco e Fator de Proteção</a></li>
  <li><a href="#propriedades-de-testes-diagnósticos" id="toc-propriedades-de-testes-diagnósticos" class="nav-link" data-scroll-target="#propriedades-de-testes-diagnósticos">Propriedades de Testes Diagnósticos</a>
  <ul class="collapse">
  <li><a href="#sensibilidade-e-especificidade" id="toc-sensibilidade-e-especificidade" class="nav-link" data-scroll-target="#sensibilidade-e-especificidade">Sensibilidade e Especificidade</a></li>
  <li><a href="#valor-preditivo-positivo-vpp-e-valor-preditivo-negativo-vpn" id="toc-valor-preditivo-positivo-vpp-e-valor-preditivo-negativo-vpn" class="nav-link" data-scroll-target="#valor-preditivo-positivo-vpp-e-valor-preditivo-negativo-vpn">Valor Preditivo Positivo (VPP) e Valor Preditivo Negativo (VPN)</a></li>
  <li><a href="#razão-de-verossimilhança-positiva-e-negativa" id="toc-razão-de-verossimilhança-positiva-e-negativa" class="nav-link" data-scroll-target="#razão-de-verossimilhança-positiva-e-negativa">Razão de Verossimilhança Positiva e Negativa</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Propriedades de Testes Diagnósticos</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="risco-absoluto-fator-de-risco-e-fator-de-proteção" class="level1">
<h1>Risco Absoluto, Fator de Risco e Fator de Proteção</h1>
<p>Risco absoluto é a probabilidade de um evento ocorrer em um determinado grupo de pessoas sob risco de ocorrência deste evento. No universo da saúde eventos como ocorrência de doença, complicações, internação, contágio, óbito, amputação e morte são alguns exemplos de eventos. Em termos simples, é a taxa de ocorrência ou percentual de pessoas que sofrem o evento em certo período, entre a população em risco de sofrer o evento. Por exemplo: em uma escola, 10 alunos do primeiro ano do ensino médio reprovam ao final do ano. O total de alunos é de 200 alunos no primeiro ano. 10 alunos de 200 = 0,5% é o risco de reprovar de ano no primeiro ano. Ao mesmo tempo, de 150 alunos que concluem o ensino médio, 100 alunos conseguem uma vaga na faculdade. 100 alunos de 150 = 66% é o risco de aprovação no vestibular entre os alunos desta escola. Note que risco absoluto não se aplica necessariamente a um evento ruim ou algo indesejável, mas sim um evento específico de ocorrer entre uma população em risco de que este evento ocorra – repetir de ano ou passar no vestibular são eventos para os quais alunos desta escola estão “em risco de”. Eles fazem parte da população de risco para tanto “ser reprovado de ano” quanto para “passar no vestibular”.</p>
<p>Mas será que ser reprovado no ensino médio ou ser aprovado no vestibular acontece aleatoriamente? Seria resultado de um sorteio aleatório? Ou será que existem características que fazem com que alguns alunos sejam mais propensos a reprovar – e características que fazem com que alunos sejam mais propensos a serem aprovados no vestibular? Quais seriam então estes fatores que fazem com que “o risco de reprovar” no ensino médio diminuam ou “o risco de ser aprovado no vestibular” aumentem? Para isto, vamos recuperar o conceito de FATOR DE RISCO.</p>
<p><strong>FATOR DE RISCO</strong> é qualquer característica do indivíduo – ou exposição sobre o indivíduo – que aumenta a chance de ocorrência do evento sobre este indivíduo. Ter uma rotina diária e um plano de estudos preparatório para o vestibular seria um fator de risco para aprovação no vestibular. Por outro lado, viver em um ambiente de privação econômica (desemprego, baixa renda) e ser exposto a situações de violência familiar e social podem ser fatores de risco para reprovação na escola. Isso não significa que alunos organizados e com rotina consistente de estudo serão sempre aprovados, muito menos que viver na pobreza signifique que o aluno não chegará a concluir o ensino médio. FATOR DE RISCO é apenas fator de risco, e não um fator DETERMINÍSTICO. <a href="https://educacaopublica.cecierj.edu.br/artigos/18/14/fatores-que-facilitam-e-dificultam-a-aprendizagem" class="uri">https://educacaopublica.cecierj.edu.br/artigos/18/14/fatores-que-facilitam-e-dificultam-a-aprendizagem</a></p>
<p>Usualmente chamamos de FATOR DE PROTEÇÃO algum fator de risco que proteja o indivíduo da ocorrência de um evento indesejado ou que o favoreça para ocorrência de um evento de sucesso; e mantemos o uso de FATOR DE RISCO para situações de dano ou prejuízo. Fumar tabaco é um FATOR DE RISCO para doença pulmonar obstrutiva crônica. Dirigir sem usar sinto de segurança é um FATOR DE RISCO para morte ou lesão grave em caso de colisão.</p>
<p>No Ciclo 2 deste módulo falamos sobre <strong>RISCO RELATIVO</strong>: razão entre dois riscos absolutos, um entre expostos ao fator de interesse (risco ou proteção) e outro entre os não expostos. Como se trata de uma RAZÃO (multiplicação), o valor de igualdade será 1. Ou seja, se a razão entre o risco entre expostos e o risco entre não-expostos for igual a 1, isto significa que o fator de interesse não influi em nada na ocorrência do evento. Contudo, se a razão for menor do que 1, será um FATOR DE PROTEÇÃO. Se a razão for mais do que 1, será um FATOR DE RISCO.</p>
</section>
<section id="propriedades-de-testes-diagnósticos" class="level1">
<h1>Propriedades de Testes Diagnósticos</h1>
<p><strong>T</strong>estes diagnósticos podem ser exames de laboratório, de imagem, <strong>achados clínicos</strong> do exame físico ou até mesmo informações dadas pelo paciente durante a entrevista. Todos os testes diagnósticos possuem medidas de desempenho chamadas <strong>propriedades diagnósticas</strong>. As principais propriedades são <strong>sensibilidade, especificidade, valor preditivo positivo, valor preditivo negativo</strong> e as <strong>razões de verossimilhança</strong> positiva e negativa. Em termos simples, essas propriedades quantificam <strong>o quão bem um teste consegue distinguir doentes de não doentes</strong>.</p>
<p>Elas respondem a perguntas como: “entre os doentes, quantos deles o teste consegue realmente detectar?” (<strong>Sensibilidade</strong>) ou “entre os não-doentes, para quantos deles o teste será negativo?” (<strong>Especificidade</strong>). Os <strong>Valores Preditivos</strong> indicam o grau de confiança que podemos ter no resultado encontrado em um paciente que vive em um determinado cenário. E as <strong>Razões de Verossimilhança</strong> indicam quanto um resultado modifica a probabilidade de doença.</p>
<section id="sensibilidade-e-especificidade" class="level2">
<h2 class="anchored" data-anchor-id="sensibilidade-e-especificidade">Sensibilidade e Especificidade</h2>
<p><strong>Sensibilidade</strong>&nbsp;é a capacidade do teste identificar corretamente aqueles que&nbsp;<strong>têm</strong>&nbsp;a doença – isto é, dos doentes, qual proporção testa positivo. Um teste altamente sensível pega quase todos os doentes e terá poucos falsos negativos.&nbsp;<strong>Especificidade</strong>&nbsp;é a capacidade de identificar corretamente quem&nbsp;<strong>não tem</strong>&nbsp;a doença – ou seja, dos saudáveis, qual proporção testa negativo. Um teste <strong>altamente específico</strong> praticamente só resulta positivo se a pessoa realmente tiver a doença e terá poucos “falsos positivos”. Um teste altamente sensível não deixará que quase nenhum paciente que possui a doença passar desapercebido – na quase totalidade das vezes o resultado será positivo.</p>
<p>Esses dois parâmetros permitem avaliar o&nbsp;<strong>equilíbrio</strong>&nbsp;do teste. Um teste perfeito teria 100% de sensibilidade&nbsp;<em>e</em>&nbsp;100% de especificidade – pega todos os doentes e nunca acusa positivo nos saudáveis – mas na realidade isso é muito raro. Em geral, há ganhos e perdas para cada teste: se você quer <strong>muita sensibilidade</strong> (não perder nenhum caso), talvez tenha que tolerar alguns falsos alarmes (menor especificidade). Ao contrário, se precisar de alta especificidade (nenhum falso alarme), talvez o teste só pegue os casos mais óbvios e perca muitos doentes com sintomas brandos (menor sensibilidade).&nbsp;</p>
<p><strong>Entender esse equilíbrio ajuda a escolher o teste certo para cada situação</strong>. Por exemplo, para rastrear uma doença grave na população geral (ex.: triagem neonatal ou teste de HIV em doação de sangue), devemos priorizar a sensibilidade do teste, pois não queremos perder nenhum caso verdadeiramente positivo, mesmo que isto nos custe ter alguns falsos positivos e, posteriormente realizar com estes outros testes mais específicos para confirmar ou descartar a doença. Já para confirmar um diagnóstico suspeito, preferimos teste específico – um resultado positivo praticamente garante que o paciente tem a doença.</p>
<p>Para doação de sangue, muitos testes de triagem são realizados com o sangue coletado. Todos são testes muito sensíveis. Caso o resultado de algum deles venha positivo, o doador é convocado a realizar um segundo teste confirmatório, este mais específico do que o primeiro. Mas por que não fazem logo um teste específico? Provavelmente porque este teste mais específico perde em sensibilidade para o primeiro.</p>
<p>Veja o exemplo abaixo. Imagine um cenário com 1000 pacientes sendo testados. Sabemos que a prevalência da doença em questão é de 10%. De cada 1000 pacientes, 100 tem a doença testada e 900 não a tem. Para facilitar nosso aprendizado, imagine que nós já sabemos quem são os pacientes que tem ou não tem a doença – imagine que temos um teste perfeito, padrão-ouro, que nos informa quem são os 100 doentes e quem são os 900 hígidos.</p>
<p>Vamos agora aplicar um teste diagnóstico novo, mais barato e simples de ser realizado do que o nosso padrão-ouro. Queremos que este teste seja utilizado como teste inicial de triagem para esta doença e que seja utilizado na população geral, em larga escala. Para isto, fizemos uma avaliação deste novo teste nesta população de pacientes previamente diagnosticados (100 com a doença e 900 sem a doença).</p>
<p>Todos os 1000 pacientes fizeram o novo teste. Dentre aqueles que tinham a doença, 87 apresentaram resultado positivo e 13 negativo. Ou seja, apenas 87% dos pacientes doentes deram positivo com o nosso teste – a sensibilidade do nosso teste é de 87%. Por outro lado, dos 900 pacientes sem a doença, 865 apresentaram resultado negativo, como esperado. Porém, 35 deram resultado positivo (falso-positivo). Isto significa que o teste pode resultar positivo em situações diferentes do esperado. O teste pode resultar inespecífico em 4% dos casos. A especificidade do teste é de 96%.</p>
<p>Concluímos aqui que nosso teste é mais específico do que sensível. Para substituir nosso teste padrão-ouro, esperávamos que nosso teste fosse mais sensível. Infelizmente ele não foi capaz de detectar 13% dos pacientes doentes, o que não é um bom sinal para um teste de triagem.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 11%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>Pessoa com a doença</td>
<td>Pessoa sem a doença</td>
<td>Total</td>
</tr>
<tr class="even">
<td>Teste positivo</td>
<td>87</td>
<td>35</td>
<td>122</td>
</tr>
<tr class="odd">
<td>Teste negativo</td>
<td>13</td>
<td>865</td>
<td>878</td>
</tr>
<tr class="even">
<td>Total</td>
<td>100</td>
<td>900</td>
<td>1000</td>
</tr>
</tbody>
</table>
</section>
<section id="valor-preditivo-positivo-vpp-e-valor-preditivo-negativo-vpn" class="level2">
<h2 class="anchored" data-anchor-id="valor-preditivo-positivo-vpp-e-valor-preditivo-negativo-vpn">Valor Preditivo Positivo (VPP) e Valor Preditivo Negativo (VPN)</h2>
<p>Os&nbsp;<strong>valores preditivos</strong>&nbsp;dão a perspectiva do resultado encontrado com o teste para a probabilidade de que o resultado esteja correto para a condição. Ou seja, respondem:&nbsp;<strong>“Dado o resultado do teste, qual a probabilidade de ele ser verdadeiro?”</strong>.</p>
<p>Desta forma, o&nbsp;<strong>valor preditivo positivo (VPP)</strong>&nbsp;é a probabilidade de realmente ter a doença quando o teste resultou&nbsp;positivo, enquanto o&nbsp;<strong>valor preditivo negativo (VPN)</strong>&nbsp;é a probabilidade de não ter a doença quando o teste veio&nbsp;negativo.</p>
<p>Em outras palavras, entre todos os resultados positivos, qual porcentagem é de verdadeiros positivos (pacientes de fato doentes) – ou para o VPN, entre todos os negativos, quantos são verdadeiros negativos (pessoas saudáveis mesmo).</p>
<p>Simplificando, podemos dizer que o VPP nos mostra a confiança no resultado positivo e que o VPN nos mostra a confiança no resultado negativo.</p>
<p>Por que esta medida é importante?</p>
<p>Os valores preditivos são úteis na prática clínica porque&nbsp;<strong>é exatamente assim que nós e pacientes pensamos na maioria das vezes. Quantas vezes você já ouviu um paciente falar:</strong> “Doutor, meu exame deu positivo… e agora? Será que tenho mesmo essa doença?”.</p>
<p>Diferente de sensibilidade/especificidade,&nbsp;<strong>os valores preditivos não são fixos do teste – eles variam conforme a prevalência da doença na população testada</strong>. Isso é&nbsp;<em>crítico</em>: um mesmo teste pode ter VPP alto num contexto e baixo noutro. Se a doença é rara (pouco prevalente), mesmo um teste com ótima especificidade pode acabar tendo mais falsos positivos do que verdadeiros positivos – ou seja, VPP baixo. Já se a doença é muito comum no seu cenário, um resultado positivo tem grande chance de ser verdadeiro (VPP será alto), mas um resultado negativo pode não ser tão tranquilizador (o VPN será baixo pela alta prevalência).</p>
<p><strong>Em resumo:</strong>&nbsp;</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 32%">
<col style="width: 52%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>VPP</td>
<td>VPN</td>
</tr>
<tr class="even">
<td>Prevalência alta</td>
<td>Sobe (maior confiança no resultado positivo)</td>
<td>Diminui (resultado negativo fica menos provável de ser verdadeiro negativo)</td>
</tr>
<tr class="odd">
<td>Prevalência baixa</td>
<td>Cai (muitos positivos serão falsos)</td>
<td>Aumenta (resultado negativo fica muito mais confiável)</td>
</tr>
</tbody>
</table>
<p>Esta prevalência que estamos falando aqui será importante para entendermos melhor as razões de verossimilhança.</p>
<p>No nosso exemplo acima, tínhamos a prevalência da doença hipotética? Sim! Tínhamos uma prevalência de 10%, mas este valor era artificial. Criamos esta situação selecionando pacientes com e sem a doença. No cenário real, isto muda.</p>
<p>De qualquer forma, como fazer para calcular os valores preditivos?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 11%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>Pessoa com a doença</td>
<td>Pessoa sem a doença</td>
<td>Total</td>
</tr>
<tr class="even">
<td>Teste positivo</td>
<td>87</td>
<td>35</td>
<td>122</td>
</tr>
<tr class="odd">
<td>Teste negativo</td>
<td>13</td>
<td>865</td>
<td>878</td>
</tr>
<tr class="even">
<td>Total</td>
<td>100</td>
<td>900</td>
<td>1000</td>
</tr>
</tbody>
</table>
<p>Se o valor preditivo positivo é a proporção de verdadeiros positivos sobre todos os positivos, teremos então 87de 122, o que resulta em 71,3%. O valor preditivo negativo será a proporção de verdadeiros negativos entre todos com resultado negativo (865 de 878), o que resulta em 98,5%. Em outras palavras, neste cenário de 10% de prevalência da doença, o resultado negativo é muito provavelmente um verdadeiro negativo. Se o resultado for positivo, não podemos dizer o mesmo.</p>
</section>
<section id="razão-de-verossimilhança-positiva-e-negativa" class="level2">
<h2 class="anchored" data-anchor-id="razão-de-verossimilhança-positiva-e-negativa">Razão de Verossimilhança Positiva e Negativa</h2>
<p>As&nbsp;<strong>razões de verossimilhança (RV)</strong>&nbsp;são medidas que combinam sensibilidade e especificidade em um único número, indicando&nbsp;<strong>quanto aquele resultado do teste muda as chances do paciente ter (ou não ter) a doença</strong>. Especificamente, a&nbsp;<strong>razão de verossimilhança positiva (RV+)</strong>&nbsp;nos diz&nbsp;<em>quantas vezes mais provável</em>&nbsp;será o diagnóstico para o paciente dado que o teste resultou positivo. &nbsp;A <strong>razão de verossimilhança negativa (RV-)</strong>&nbsp;nos diz o oposto, ou seja, <em>quantas vezes menos provável</em>&nbsp;será o diagnóstico em um paciente dado que o resultado do teste foi negativo.</p>
<p>O valor de igualdade da razão de verossimilhança sempre será 1. Quanto maior for o valor da RV+ (quanto mais acima de 1) maior será a probabilidade de o paciente ter a doença com o resultado positivo do teste – quanto maior, mais aumenta a chance da doença. Quanto menor for o valor da RV- (quanto mais abaixo de 1) menor será a probabilidade de o paciente ter a doença, caso o teste resulte negativo – quanto menor, mais reduz a chance da doença.</p>
<p>Falando em fórmulas, estas são um pouco mais complicadas do que as anteriores. Não se preocupe em decorá-las, mas sim em entender o que significam.</p>
<p>Relembrando a tabela anterior comparando nosso novo teste com o padrão-ouro temos o seguinte:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>Pessoa com a doença</td>
<td>Pessoa sem a doença</td>
<td>Total</td>
</tr>
<tr class="even">
<td>Teste positivo</td>
<td>A</td>
<td>B</td>
<td>A+B</td>
</tr>
<tr class="odd">
<td>Teste negativo</td>
<td>C</td>
<td>D</td>
<td>C+D</td>
</tr>
<tr class="even">
<td>Total</td>
<td>A+C</td>
<td>B+D</td>
<td>A+B+C+D</td>
</tr>
</tbody>
</table>
<p>As fórmulas para as razões de verossimilhança são as seguintes.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 55%">
<col style="width: 44%">
</colgroup>
<tbody>
<tr class="odd">
<td>Razão de verossimilhança Positiva (RV+)</td>
<td><p>1−Especificidade/Sensibilidade</p>
<p>ou</p>
<p>B/(B+D) /A/(A+C)​</p></td>
</tr>
<tr class="even">
<td>Razão de verossimilhança Negativa (RV-)</td>
<td><p>Especificidade/(1−Sensibilidade)</p>
<p>ou</p>
<p>D/(B+D) /C/(A+C)​</p></td>
</tr>
</tbody>
</table>
<p>Desta forma, temos que:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 9%">
</colgroup>
<tbody>
<tr class="odd">
<td>Razão de verossimilhança positiva</td>
<td>22.4</td>
</tr>
<tr class="even">
<td>Razão de verossimilhança negativa</td>
<td>0.13</td>
</tr>
</tbody>
</table>
<p>Usando as informações da tabela acima, temos o seguinte sumário com explicações e fórmulas:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 42%">
<col style="width: 19%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Propriedade</strong></td>
<td><strong>Explicação</strong></td>
<td><strong>Fórmula</strong></td>
<td><strong>Valores do exemplo</strong></td>
</tr>
<tr class="even">
<td><strong>Sensibilidade</strong></td>
<td>positivos entre os doentes</td>
<td>A / A+C</td>
<td>0.87</td>
</tr>
<tr class="odd">
<td><strong>Especificidade</strong></td>
<td>negativos entre os não-doentes</td>
<td>D / B+D</td>
<td>0.96</td>
</tr>
<tr class="even">
<td><strong>Valor Preditivo Positivo</strong></td>
<td>doentes entre os positivos</td>
<td>A / A+B</td>
<td>0.71</td>
</tr>
<tr class="odd">
<td><strong>Valor Preditivo Negativo</strong></td>
<td>não-doentes entre os negativos</td>
<td>D / C+D</td>
<td>0.98</td>
</tr>
<tr class="even">
<td><strong>Razão de verossimilhança Positiva</strong></td>
<td>Quanto aumenta a probabilidade do diagnóstico, com o resultado positivo</td>
<td><p>1−Especificidade/Sensibilidade</p>
<p>ou</p>
<p>B/(B+D) /A/(A+C)​</p></td>
<td>22.4</td>
</tr>
<tr class="odd">
<td><strong>Razão de verossimilhança Negativa</strong></td>
<td>Quanto diminui a probabilidade do diagnóstico, com o resultado negativo</td>
<td><p>Especificidade/(1−Sensibilidade)</p>
<p>ou</p>
<p>D/(B+D) /C/(A+C)​</p></td>
<td>0.13</td>
</tr>
</tbody>
</table>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./MBE.html" class="pagination-link" aria-label="Medicina Baseada em Evidências">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Medicina Baseada em Evidências</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./finding_consultancies.html" class="pagination-link" aria-label="Consultancies in International Health">
        <span class="nav-page-text"><span class="chapter-title">Consultancies in International Health</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>